config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :renters
  resources :managers
  resources :properties
  resources :events, only: [:create, :destroy]
  resources :sessions, only: [:create, :new, :destroy]

  get 'splash/index'

  root 'properties#index'

  get "logout", :to => "sessions#destroy", :as => "logout"
  get "login", :to => "sessions#new", :as => "login"
  get "signup", :to => "users#new", :as => "signup"

  get "search", :to => "splash#search", :as => "search"
  get "search_itineraries" => 'splash#search_itineraries', as: 'search_itineraries'

end

app/models/renter.rb
class Renter < ActiveRecord::Base
  before_save { |user| user.email = email.downcase }
  validates :email, uniqueness: true

  def display_name
    # return first_name.titleize + ' ' + last_name[0].capitalize
    first_name + ' ' + last_name
  end
end

app/controllers/renters_controller.rb
class RentersController < ApplicationController
  respond_to :js, :html, :json
  before_filter :require_login

  def new
    @renter = Renter.new
    respond_with @renter
  end

  def update
    Renter.update(params[:id],renter_params)

    redirect_to :back
  end

  def create
    @renter = Renter.new(renter_params)
    @renter.save
    respond_with @renter
  end

  def index
    @renter = Renter.new
    @renters = Renter.order(:last_name);
    @title = "Renter Directory";

    respond_with(@renters) do |format|
      format.json {
        @mList = @renters.map { |u| { :id => u.id, :name => u.first_name + " " + u.last_name } }
        @mList = @mList.find_all{ |u| u[:name].downcase.include?(params[:q].downcase) } if params[:q]
        render :json => @mList
      }
    end
  end
  
  def show
    @renter = Renter.find(params[:id])
    respond_with @renter
  end

  def destroy
    @renter = Renter.find(params[:id])
    @renter.destroy
    redirect_to :back
  end

  private

  def renter_params
    params.require(:renter).permit(
      :email,
      :phone,
      :first_name, 
      :last_name,
      :company_name
    )
  end
end

app/helpers/renters_helper.rb
module RentersHelper
end

app/views/renters/index.html.haml
- content_for :modal do
  %h1 Edit Renters
  = form_tag(renters_path, :url => { :action => "update" }, :id => 'renter_edit_form', :method => :patch ) do
    %fieldset
      = fields_for :renter do |f|
        = f.email_field :email, :placeholder => "Email", :class => "req", :autocomplete => :off
        = f.text_field :first_name, :placeholder => 'First Name', :class => 'req', :autocomplete => :off
        = f.text_field :last_name, :placeholder => 'Last Name', :class => 'req', :autocomplete => :off
        = f.text_field :company_name, :placeholder => 'Company Name', :class => 'req', :autocomplete => :off
      = submit_tag "Edit", :class => "edit"

- content_for :head do
  %script{:type => "text/javascript"}                           |
    $(function() {                                              |
      $('a.edit').click(function() {                            |
        var id = $(this).attr('id');                            |
        $.getJSON('/renters/' + id, function(data, status) {    |
          console.log(data);                                    |
          var f = $('form#renter_edit_form');                   |
          var fields = [ 'first_name', 'last_name', 'email', 'company_name' ];  |
          var numFields = fields.length;                        |
          for (var i = 0; i < numFields; i++) {                 |
            var field = fields[i];                              |
            var field_id  = 'renter_' + field;                  |
            f.find('input#' + field_id).attr('value', data[field]); |
          }                                                     |
        });                                                     |
        $('form#renter_edit_form').each(function() {            |
          $(this).attr('action', $(this).attr('action') + '/' + id) |
        })                                                      |
      })                                                        |
    })                                                          |

.form-wrapper
  .form-info
    %h1 Create New Renter

    .error-messages
      - for message in @renter.errors.full_messages
        %p #{message}

  = form_for(@renter, :html => { :class => 'form-fields' }) do |f|
    %fieldset
      = f.email_field :email, :placeholder => "Email", :class => "req", :autocomplete => :off
      = f.phone_field :phone, :placeholder => "Phone Number", :class => "req", :autocomplete => :off
      = f.text_field :first_name, :placeholder => 'First Name', :class => 'req', :autocomplete => :off
      = f.text_field :last_name, :placeholder => 'Last Name', :class => 'req', :autocomplete => :off
      = f.text_field :company_name, :placeholder => 'Company Name', :class => 'req', :autocomplete => :off
    = f.submit "Create", :class => "submit"

%br
%br

.directory
  %h1 View Renters
  %table
    %thead
      %tr
        %th Display Name
        %th Email
        %th Phone
        %th Company Name
        %th Modify
    %tbody
    - @renters.each do |renter|
      %tr
        %th= link_to renter.display_name, renter_url(renter)
        %th= renter.email
        %th= renter.phone
        %th= renter.company_name
        %th
          = link_to image_tag("iconmonstr-pencil-10-icon.svg", :alt => "Edit"), "#modal_content", :class => "edit", :id => renter.id, :name => "modal_content", :rel => "leanModal"
          = link_to image_tag("iconmonstr-x-mark-icon.svg", :alt => "Delete"), renter_url(renter.id), method: :delete, remote: false

app/views/renters/new.html.haml
.form-wrapper
  .form-info
    %h1 Create New Renter

    .error-messages
      - for message in @renter.errors.full_messages
        %p #{message}

  = form_for(@renter, :html => { :class => 'form-fields' }) do |f|
    %fieldset
      = f.email_field :email, :placeholder => "Email", :class => "req", :autocomplete => :off
      = f.phone_field :phone, :placeholder => "Phone Number", :class => "req", :autocomplete => :off
      = f.text_field :first_name, :placeholder => 'First Name', :class => 'req', :autocomplete => :off
      = f.text_field :last_name, :placeholder => 'Last Name', :class => 'req', :autocomplete => :off
      = f.text_field :company_name, :placeholder => 'Company Name', :class => 'req', :autocomplete => :off
    = f.submit "Create", :class => "submit"

app/views/renters/show.html.haml
.profile
  %h1 #{@renter.display_name}'s Profile
  %table
    %tbody
      %tr
        %th First Name
        %th #{@renter.first_name}
      %tr
        %th Last Name
        %th #{@renter.last_name}
      %tr
        %th Email
        %th #{@renter.email}
      %tr
        %th Phone
        %th #{@renter.phone}
      %tr
        %th Company Name
        %th #{@renter.company_name}
  
  = link_to "Back", renters_url