config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :renters
  resources :managers
  resources :properties
  resources :events, only: [:create, :destroy]
  resources :sessions, only: [:create, :new, :destroy]

  get 'splash/index'

  root 'properties#index'

  get "logout", :to => "sessions#destroy", :as => "logout"
  get "login", :to => "sessions#new", :as => "login"
  get "signup", :to => "users#new", :as => "signup"

  get "search", :to => "splash#search", :as => "search"
  get "search_itineraries" => 'splash#search_itineraries', as: 'search_itineraries'

end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_secure_password
  before_save { |user| user.email = email.downcase }
  validates :email, uniqueness: true

  has_many :events

  def display_name
    # return first_name.titleize + ' ' + last_name[0].capitalize
    # first_name.titleize + ' ' + last_name.titleize
    first_name + ' ' + last_name
  end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  respond_to :js, :html, :json
  before_filter :require_login, :except => [:create]

  def new
    @manager = Manager.new
    respond_with @manager
  end

  def update
    Manager.update(params[:id],manager_params)

    redirect_to :back
  end

  def create
    @manager = Manager.new(manager_params)
    
    if @manager.save
      session[:user_id] = @manager.id
    end

    respond_with @manager
  end

  def show
    @manager = Manager.find(params[:id])
    respond_with @manager
  end

  def index
    @manager = Manager.new
    @managers = Manager.order(:last_name);
    @title = "Manager Directory";

    respond_with(@managers) do |format|
      format.json {
        @mList = @managers.map { |u| { :id => u.id, :name => u.first_name + " " + u.last_name } }
        @mList = @mList.find_all{ |u| u[:name].downcase.include?(params[:q].downcase) } if params[:q]
        render :json => @mList
      }
    end
  end

  def destroy
    @manager = Manager.find(params[:id])
    @manager.destroy
    redirect_to :back
  end
  private

  def manager_params
    params.require(:manager).permit(
      :email,
      :first_name, 
      :last_name,      
      :password, 
      :password_confirmation
    )
  end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/index.html.haml
- content_for :modal do
  %h1 Edit Manager
  = form_tag(managers_path, :url => { :action => "update" }, :id => 'manager_edit_form', :method => :patch ) do
    %fieldset
      = fields_for :manager do |f|
        = f.email_field :email, :placeholder => "Email", :class => "req", :autocomplete => :off
        = f.text_field :first_name, :placeholder => 'First Name', :class => 'req', :autocomplete => :off
        = f.text_field :last_name, :placeholder => 'Last Name', :class => 'req', :autocomplete => :off
        = f.password_field :password, :placeholder => "Password", :class => "req", :autocomplete => :off
        = f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => "req", :autocomplete => :off
      = submit_tag "Edit", :class => "edit"

- content_for :head do
  %script{:type => "text/javascript"}                           |
    $(function() {                                              |
      $('a.edit').click(function() {                            |
        var id = $(this).attr('id');                            |
        $.getJSON('/managers/' + id, function(data, status) {   |
          console.log(data);                                    |
          var f = $('form#manager_edit_form');                  |
          var fields = [ 'first_name', 'last_name', 'email' ];  |
          var numFields = fields.length;                        |
          for (var i = 0; i < numFields; i++) {                 |
            var field = fields[i];                              |
            var field_id  = 'manager_' + field;                 |
            f.find('input#' + field_id).attr('value', data[field]); |
          }                                                     |
        });                                                     |
        $('form#manager_edit_form').each(function() {           |
          $(this).attr('action', $(this).attr('action') + '/' + id) |
        })                                                      |
      })                                                        |
    })                                                          |

.form-wrapper
  .form-info
    %h1 Create Property Manager

    .error-messages
      - for message in @manager.errors.full_messages
        %p #{message}

  = form_for(@manager, :html => { :class => 'form-fields' }) do |f|
    %fieldset
      = f.email_field :email, :placeholder => "Email", :class => "req", :autocomplete => :off
      = f.text_field :first_name, :placeholder => 'First Name', :class => 'req', :autocomplete => :off
      = f.text_field :last_name, :placeholder => 'Last Name', :class => 'req', :autocomplete => :off
      = f.password_field :password, :placeholder => "Password", :class => "req", :autocomplete => :off
      = f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => "req", :autocomplete => :off
    = f.submit "Create", :class => "submit"
%br
%br

.directory
  %h1 View Property Managers
  %table
    %thead
      %tr
        %th Display Name
        %th Email
        %th Modify
    %tbody
    - @managers.each do |m|
      %tr
        %th= link_to m.display_name, manager_url(m)
        %th= m.email
        %th
          = link_to image_tag("iconmonstr-pencil-10-icon.svg", :alt => "Edit"), "#modal_content", :class => "edit", :id => m.id, :name => "modal_content", :rel => "leanModal"
          = link_to image_tag("iconmonstr-x-mark-icon.svg", :alt => "Delete"), manager_url(m.id), method: :delete, remote: false if current_user != m

app/views/managers/new.html.haml
.form-wrapper
  .form-info
    %h1 Create Property Manager

    .error-messages
      - for message in @manager.errors.full_messages
        %p #{message}

  = form_for(@manager, :html => { :class => 'form-fields' }) do |f|
    %fieldset
      = f.email_field :email, :placeholder => "Email", :class => "req", :autocomplete => :off
      = f.text_field :first_name, :placeholder => 'First Name', :class => 'req', :autocomplete => :off
      = f.text_field :last_name, :placeholder => 'Last Name', :class => 'req', :autocomplete => :off
      = f.password_field :password, :placeholder => "Password", :class => "req", :autocomplete => :off
      = f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => "req", :autocomplete => :off
    = f.submit "Create", :class => "submit"

app/views/managers/show.html.haml
.profile
  %h1 #{@manager.display_name}'s Profile
  %table
    %tbody
      %tr
        %th First Name
        %th #{@manager.first_name}
      %tr
        %th Last Name
        %th #{@manager.last_name}
      %tr
        %th Email
        %th #{@manager.email}
  
  = link_to "Back", managers_url