config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :renters
  resources :managers
  resources :properties
  resources :events, only: [:create, :destroy]
  resources :sessions, only: [:create, :new, :destroy]

  get 'splash/index'

  root 'properties#index'

  get "logout", :to => "sessions#destroy", :as => "logout"
  get "login", :to => "sessions#new", :as => "login"
  get "signup", :to => "users#new", :as => "signup"

  get "search", :to => "splash#search", :as => "search"
  get "search_itineraries" => 'splash#search_itineraries', as: 'search_itineraries'

end

app/views/shared/_sidebar.html.haml
%section{:class => "fixed-sidebar col3"}
  %nav.title
    = link_to "ExecHQ Console", root_url
  - if current_user
    .welcome Welcome, #{current_user.display_name}!
  %nav
    = link_to "Users", root_url, :class => "h3"
    = link_to "Companies", companies_url, :class => ( current_page?( companies_url ) ? "small active" : "small") 
    -# = link_to "Create Manager", new_manager_url, :class => ( current_page?( new_manager_url ) ? "small active" : "small") 
    = link_to "Managers", managers_url, :class => ( current_page?( managers_url ) ? "small active" : "small") 
    -# = link_to "Create Renter", new_renter_url, :class => ( current_page?( new_renter_url ) ? "small active" : "small")
    = link_to "Renters", renters_url, :class => ( current_page?( renters_url ) ? "small active" : "small")
    - if current_user
      = link_to "My Properties", root_url
      = link_to "Add Property", new_property_url, :class => ( current_page?( new_property_url ) ? "small active" : "small")
      = link_to "Show Properties", properties_url, :class => ( current_page?( properties_url ) ? "small active" : "small")

      = link_to "Sign Out", logout_url
      //= link_to "Modal Test", "#modal_content", :id => "go", :name => "modal_content", :rel => "leanModal"